### ISSUE TITLE
Fatal Exception on Windows 10

### ISSUE THREAD

**Issue by omni-** [NyxStudios/TShock#1028]
After starting the server with no extra plugins, this exception is thrown:

[Server API] Info Plugin TShock v4.3.5.0 (by The TShock Team) initiated.
Exception during world metadata load.
If you are using -autocreate, it is safe to ignore this.
[Server API] Error Server crashed due to an unhandled exception:
System.InvalidOperationException: Failed to compare two elements in the array. -
--> System.NullReferenceException: Object reference not set to an instance of an
 object.
   at Terraria.Main.WorldListSortMethod(WorldFileData data1, WorldFileData data2
)
   at System.Array.FunctorComparer`1.Compare(T x, T y)
   at System.Collections.Generic.ArraySortHelper`1.SwapIfGreater(T[] keys, IComp
arer`1 comparer, Int32 a, Int32 b)
   at System.Collections.Generic.ArraySortHelper`1.DepthLimitedQuickSort(T[] key
s, Int32 left, Int32 right, IComparer`1 comparer, Int32 depthLimit)
   at System.Collections.Generic.ArraySortHelper`1.Sort(T[] keys, Int32 index, I
nt32 length, IComparer`1 comparer)
   --- End of inner exception stack trace ---
   at System.Collections.Generic.ArraySortHelper`1.Sort(T[] keys, Int32 index, I
nt32 length, IComparer`1 comparer)
   at System.Array.Sort[T](T[] array, Int32 index, Int32 length, IComparer`1 com
parer)
   at System.Collections.Generic.List`1.Sort(Comparison`1 comparison)
   at Terraria.Main.LoadWorlds()
   at Terraria.Main.DedServ()
   at Terraria.ProgramServer.InnerStart(String[] args)

**Comment by raked** [comment]
I had this same error, try sorting out your worlds. I had corrupted ones that broke it.

**Comment by nicatronTg** [comment]
This is on the help guide.
