### ISSUE TITLE
every time it starts it crashs

### ISSUE THREAD

**Issue by chknlttl2004** [NyxStudios/TShock#1052]
every time i click it this pops up

[Server API] Error Server crashed due to an unhandled exception:
System.InvalidOperationException: Failed to compare two elements in the array. -
--> System.NullReferenceException: Object reference not set to an instance of an
 object.
   at Terraria.Main.WorldListSortMethod(WorldFileData data1, WorldFileData data2
)
   at System.Array.FunctorComparer`1.Compare(T x, T y)
   at System.Collections.Generic.ArraySortHelper`1.SwapIfGreater(T[] keys, IComp
arer`1 comparer, Int32 a, Int32 b)
   at System.Collections.Generic.ArraySortHelper`1.IntroSort(T[] keys, Int32 lo,
 Int32 hi, Int32 depthLimit, IComparer`1 comparer)
   at System.Collections.Generic.ArraySortHelper`1.IntrospectiveSort(T[] keys, I
nt32 left, Int32 length, IComparer`1 comparer)
   at System.Collections.Generic.ArraySortHelper`1.Sort(T[] keys, Int32 index, I
nt32 length, IComparer`1 comparer)
   --- End of inner exception stack trace ---
   at System.Collections.Generic.ArraySortHelper`1.Sort(T[] keys, Int32 index, I
nt32 length, IComparer`1 comparer)
   at System.Array.Sort[T](T[] array, Int32 index, Int32 length, IComparer`1 com
parer)
   at System.Collections.Generic.List`1.Sort(Comparison`1 comparison)
   at Terraria.Main.LoadWorlds()
   at Terraria.Main.DedServ()
   at Terraria.ProgramServer.InnerStart(String[] args)

**Comment by chknlttl2004** [comment]
it doesnt even let me choose a world

**Comment by nicatronTg** [comment]
The forums are for support, not Github. This question has already been answered numerous times.
