### ISSUE TITLE
Startup Error Message

### ISSUE THREAD

**Issue by Administrating** [NyxStudios/TShock#1062]
Whenever I start Tshock, I get an error message saying that it was unable to startup due to inability to read itself. This is both on the official 1.3.5 version and the prerelease of 1.3.7. The full text from the Server Logs looks like this:

[07/29/15 18:35:21] [Server API] Verbose: TerrariaApi - Server v1.19.0.0 started.
[07/29/15 18:35:21] [Server API] Verbose: 	Command line: "C:\Users\Jasper\Downloads\tshock_4.3.5-release\TerrariaServer.exe" 
[07/29/15 18:35:21] [Server API] Verbose: 	OS: Microsoft Windows NT 6.1.7601 Service Pack 1 (64bit: True)
[07/29/15 18:35:21] [Server API] Verbose: 	Mono: False
[07/29/15 18:35:21] [Server API] Error: Startup aborted due to an exception in the Server API initialization:
System.InvalidOperationException: Plugin "TShock" has thrown an exception during initialization. ---> System.Exception: Fatal TShock initialization exception. See inner exception for details. ---> System.TypeLoadException: Could not load type 'System.Collections.Generic.IReadOnlyDictionary`2' from assembly 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'.
   at Newtonsoft.Json.Utilities.CollectionUtils.IsDictionaryType(Type type)
   at Newtonsoft.Json.Serialization.DefaultContractResolver.CreateContract(Type objectType)
   at Newtonsoft.Json.Serialization.DefaultContractResolver.ResolveContract(Type type)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.Serialize(JsonWriter jsonWriter, Object value, Type objectType)
   at Newtonsoft.Json.JsonSerializer.SerializeInternal(JsonWriter jsonWriter, Object value, Type objectType)
   at Newtonsoft.Json.JsonConvert.SerializeObjectInternal(Object value, Type type, JsonSerializer jsonSerializer)
   at TShockAPI.ConfigFile.Write(Stream stream)
   at TShockAPI.ConfigFile.Write(String path)
   at TShockAPI.FileTools.SetupConfig()
   at TShockAPI.TShock.Initialize()
   --- End of inner exception stack trace ---
   at TShockAPI.TShock.Initialize()
   at TerrariaApi.Server.ServerApi.LoadPlugins()
   --- End of inner exception stack trace ---
   at TerrariaApi.Server.ServerApi.LoadPlugins()
   at TerrariaApi.Server.ServerApi.Initialize(String[] commandLineArgs, Main game)
   at Terraria.ProgramServer.InnerStart(String[] args)
[07/29/15 18:36:06] [Server API] Verbose: TerrariaApi - Server v1.19.0.0 started.
[07/29/15 18:36:06] [Server API] Verbose: 	Command line: "C:\Users\Jasper\Downloads\tshock_4.3.5-release\TerrariaServer.exe" 
[07/29/15 18:36:06] [Server API] Verbose: 	OS: Microsoft Windows NT 6.1.7601 Service Pack 1 (64bit: True)
[07/29/15 18:36:06] [Server API] Verbose: 	Mono: False
[07/29/15 18:36:06] [Server API] Error: Startup aborted due to an exception in the Server API initialization:
System.InvalidOperationException: Plugin "TShock" has thrown an exception during initialization. ---> System.Exception: Fatal TShock initialization exception. See inner exception for details. ---> System.TypeLoadException: Could not load type 'System.Collections.Generic.IReadOnlyDictionary`2' from assembly 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'.
   at Newtonsoft.Json.Utilities.CollectionUtils.IsDictionaryType(Type type)
   at Newtonsoft.Json.Serialization.DefaultContractResolver.CreateContract(Type objectType)
   at Newtonsoft.Json.Serialization.DefaultContractResolver.ResolveContract(Type type)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at TShockAPI.ConfigFile.Read(Stream stream)
   at TShockAPI.ConfigFile.Read(String path)
   at TShockAPI.FileTools.SetupConfig()
   at TShockAPI.TShock.Initialize()
   --- End of inner exception stack trace ---
   at TShockAPI.TShock.Initialize()
   at TerrariaApi.Server.ServerApi.LoadPlugins()
   --- End of inner exception stack trace ---
   at TerrariaApi.Server.ServerApi.LoadPlugins()
   at TerrariaApi.Server.ServerApi.Initialize(String[] commandLineArgs, Main game)
   at Terraria.ProgramServer.InnerStart(String[] args)

**Comment by Patrikkk** [comment]
Holy molly thats a long error :D uhm try deleting your config and make it generate a new one.
(Or get a new zip from the release downloads, everything clean, see if isssue still occurs then :) )

**Comment by WhiteXZ** [comment]
Update to .NET 4.5
