### ISSUE TITLE
Server suddenly stops working and crashes immediately.

### ISSUE THREAD

**Issue by TeeriaLLC** [NyxStudios/TShock#1077]
I have no way to reproduce this issue, it has happened twice in the last 10 minutes and don't really know what to do with this. Same as the last issue, running on the stable 4.3.8 build.

2015-08-08 18:00:37 - TShock: ERROR: System.OverflowException: Arithmetic operation resulted in an overflow.
   at TerrariaApi.Server.HookManager.InvokeNetGetData(Byte& msgId, MessageBuffer buffer, Int32& index, Int32& length)
   at Terraria.MessageBuffer.GetData(Int32 start, Int32 length)
   at Terraria.NetMessage.CheckBytes(Int32 bufferIndex)
   at Terraria.Netplay.ServerLoop(Object threadContext)
   at System.Threading.QueueUserWorkItemCallback.WaitCallback_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()

**Comment by darkunderdog** [comment]
Same issues for me

**Comment by Strinkor** [comment]
Also for me.

**Comment by TeeriaLLC** [comment]
Seems to be mainly (we think) caused by either Martians and Goblins at the same time or more than one invasion at once.

Stopped crashing after ending the invasion(s).

**Comment by Razorskills** [comment]
I had similar issues when moving a large quantity of water, but I think it was mostly a problem with using mono. Il have to test it on my Windows server and see.

**Comment by Strinkor** [comment]
I have Windows Server 2012, and have that issue, so i can suppose - it's not Mono.

**Comment by TeeriaLLC** [comment]
Confirmed Martians causing this crash.
