### ISSUE TITLE
/firework often does not seem to work.

### ISSUE THREAD

**Issue by TeeriaLLC** [NyxStudios/TShock#1083]
Below is a print screen which shows that the command /firework has failed. Upon leveling up people receive a firework above their head but most of the time it fails to do so.

https://gyazo.com/7ba9ddc3714f29b1ef390b64c386b5e0

**Comment by SmallSansSerif** [comment]
Yes, I've seen that in the log as well. It's not consistent though.

**Comment by WhiteXZ** [comment]
Please provide the log.

**Comment by tlworks** [comment]
@WhiteXZ 
2016-06-26 19:15:07 - Utils: INFO: Server executed: /firework "Wmond1711" green.
2016-06-26 19:15:07 - Command: ERROR: System.NullReferenceException: Object reference not set to an instance of an object.
   at Terraria.WorldGen.KillTile(Int32 i, Int32 j, Boolean fail, Boolean effectOnly, Boolean noItem)
   at Terraria.Projectile.Damage()
   at Terraria.Projectile.Kill()
   at TShockAPI.Commands.FireWork(CommandArgs args)
   at TShockAPI.Command.Run(String msg, Boolean silent, TSPlayer ply, List`1 parms)

**Comment by nicatronTg** [comment]
I think we should just remove this command from TShock.

**Comment by WhiteXZ** [comment]
@nicatronTg :+1:

**Comment by Patrikkk** [comment]
![ss 2016-10-11 at 02 42 37](https://cloud.githubusercontent.com/assets/5616692/19255298/c38e7b9a-8f5c-11e6-8786-971b10e2fe8e.jpg)

I have no clue how this was causing an exception in KillTile method. 
I've just tested this, it works with all colors.
