### ISSUE TITLE
SQL Exceptions with Adding Temp bans on names for players with IPs that already exist.

### ISSUE THREAD

**Issue by tysonstrange** [NyxStudios/TShock#1094]
Ok, long ongoing problem I've been trying to pin point...

I sometimes get players online that can't be banned.

Doing /ban add <player name> or /ban add <player IP> saying "failed, check logs"

Upon furthe investigation, A player on my server, JoeDude, was hacking and unable to be banned.

Checking my existing bans, I had a IP temp ban for this player already that had expired and when trying to ban him again, TShock is throwing the following exception and now allowing him to be re-banned by IP, Name or otherwise

2015-08-20 23:22:51 - Utils: INFO: Server executed: /ban addtemp joedude 1d hacking.
2015-08-20 23:22:51 - BanManager: ERROR: Mono.Data.Sqlite.SqliteException (0x80004005): Abort due to constraint violation
UNIQUE constraint failed: Bans.IP
   at Mono.Data.Sqlite.SQLite3.Reset(SqliteStatement stmt)
   at Mono.Data.Sqlite.SQLite3.Step(SqliteStatement stmt)
   at Mono.Data.Sqlite.SqliteDataReader.NextResult()
   at Mono.Data.Sqlite.SqliteDataReader..ctor(SqliteCommand cmd, CommandBehavior behave)
   at Mono.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
   at Mono.Data.Sqlite.SqliteCommand.ExecuteNonQuery()
   at TShockAPI.DB.DbExt.Query(IDbConnection olddb, String query, Object[] args)
   at TShockAPI.DB.BanManager.AddBan(String ip, String name, String uuid, String reason, Boolean exceptions, String banner, String expiration)

**Comment by tylerjwatson** [comment]
Should be fixed in bamboo build [532](http://direct.tshock.co:8085/browse/TERRA-TSHOCK-532)
