### ISSUE TITLE
TShock crashes every ~30 minutes

### ISSUE THREAD

**Issue by Strinkor** [NyxStudios/TShock#1101]
```
2015-08-30 11:37:12 - TShock: ERROR: System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Terraria.MessageBuffer.GetData(Int32 start, Int32 length)
   at Terraria.NetMessage.CheckBytes(Int32 bufferIndex)
   at Terraria.Netplay.ServerLoop(Object threadContext)
   at System.Threading.QueueUserWorkItemCallback.WaitCallback_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()
```

**Comment by tylerjwatson** [comment]
Please use a bamboo build.
