### ISSUE TITLE
Corrupt Packet.

### ISSUE THREAD

**Issue by TeeriaLLC** [NyxStudios/TShock#1108]
Do not know if this was reported, if it was. Too bad.

Running latest Bamboo build 537. Cannot be reproduced, it just happens.

[09/11/15 03:43:01] [Server API] Warning: Server could not process a packet because it was corrupt.
[09/11/15 03:43:01] [Server API] Warning: System.OverflowException: Arithmetic operation resulted in an overflow.
   at TerrariaApi.Server.HookManager.InvokeNetGetData(Byte& msgId, MessageBuffer buffer, Int32& index, Int32& length)
   at Terraria.MessageBuffer.GetData(Int32 start, Int32 length)
   at Terraria.NetMessage.CheckBytes(Int32 bufferIndex)
[09/11/15 03:43:01] [Server API] Warning: Packet contents: [44 00]

Need dump file? Ask for it.

**Comment by TeeriaLLC** [comment]
So how is this problem related to this being spammed?

https://i.gyazo.com/62e71138ee7799e44ae5be10e0ea1d15.png
