### ISSUE TITLE
IP Bans are broken and break other bans

### ISSUE THREAD

**Issue by tysonstrange** [NyxStudios/TShock#1116]
Doing a "/ban addip" doess't work.

It will add the row in the sql table, but has no affect at all.

Furthermore, then running a "/ban addtemp" on a player with the banned IP throws the followign exception

2015-09-14 11:55:15 - Utils: INFO: Panther executed: /ban addtemp "Franz GF" 7d hacking by Panther.
2015-09-14 11:55:15 - BanManager: ERROR: Mono.Data.Sqlite.SqliteException (0x80004005): SQLite error
Insufficient parameters supplied to the command
   at Mono.Data.Sqlite.SqliteStatement.BindParameter(Int32 index, SqliteParameter param)
   at Mono.Data.Sqlite.SqliteStatement.BindParameters()
   at Mono.Data.Sqlite.SqliteCommand.BuildNextCommand()
   at Mono.Data.Sqlite.SqliteCommand.GetStatement(Int32 index)
   at Mono.Data.Sqlite.SqliteDataReader.NextResult()
   at Mono.Data.Sqlite.SqliteDataReader..ctor(SqliteCommand cmd, CommandBehavior behave)
   at Mono.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
   at Mono.Data.Sqlite.SqliteCommand.ExecuteNonQuery()
   at TShockAPI.DB.DbExt.Query(IDbConnection olddb, String query, Object[] args)
   at TShockAPI.DB.BanManager.AddBan(String ip, String name, String uuid, String reason, Boolean exceptions, String banner, String expiration)

**Comment by tysonstrange** [comment]
Note that I had IP Bans disabled in config when doing this... I didn't know this was an option, but was still throwing this exception when doing the temp ban.. may still need investigation
