### ISSUE TITLE
Server won't launch

### ISSUE THREAD

**Issue by mnassassin** [NyxStudios/TShock#1168]
Hey all, i used to play with TShock almost a year ago, now i'm hosting a server and wanted to try it again. I downloaded it, Unzipped to a folder but everytime i launch "TerrariaServer.exe" i get this error:
`
`[03/09/16 00:52:28] [Server API] Verbose: TerrariaApi - Server v1.21.0.0 started.
[03/09/16 00:52:28] [Server API] Verbose: 	Command line: "C:\Users\User\Desktop\TShock Server\TerrariaServer.exe" 
[03/09/16 00:52:28] [Server API] Verbose: 	OS: Microsoft Windows NT 6.2.9200.0 (64bit: True)
[03/09/16 00:52:28] [Server API] Verbose: 	Mono: False
[03/09/16 00:52:29] [Server API] Info: Plugin TShock v4.3.9.0 (by The TShock Team) initiated.
[03/09/16 00:52:30] [Server API] Error: Server crashed due to an unhandled exception:
System.InvalidOperationException: Failed to compare two elements in the array. ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at Terraria.Main.WorldListSortMethod(WorldFileData data1, WorldFileData data2)
   at System.Array.FunctorComparer`1.Compare(T x, T y)
   at System.Collections.Generic.ArraySortHelper`1.InsertionSort(T[] keys, Int32 lo, Int32 hi, IComparer`1 comparer)
   at System.Collections.Generic.ArraySortHelper`1.IntroSort(T[] keys, Int32 lo, Int32 hi, Int32 depthLimit, IComparer`1 comparer)
   at System.Collections.Generic.ArraySortHelper`1.IntrospectiveSort(T[] keys, Int32 left, Int32 length, IComparer`1 comparer)
   at System.Collections.Generic.ArraySortHelper`1.Sort(T[] keys, Int32 index, Int32 length, IComparer`1 comparer)
   --- End of inner exception stack trace ---
   at System.Collections.Generic.ArraySortHelper`1.Sort(T[] keys, Int32 index, Int32 length, IComparer`1 comparer)
   at System.Array.Sort[T](T[] array, Int32 index, Int32 length, IComparer`1 comparer)
   at System.Collections.Generic.List`1.Sort(Comparison`1 comparison)
   at Terraria.Main.LoadWorlds()
   at Terraria.Main.DedServ()
   at Terraria.ProgramServer.InnerStart(String[] args)
[03/09/16 00:52:46] [Server API] Verbose: TerrariaApi - Server v1.21.0.0 started.
[03/09/16 00:52:46] [Server API] Verbose: 	Command line: "C:\Users\User\Desktop\TShock Server\TerrariaServer.exe" 
[03/09/16 00:52:46] [Server API] Verbose: 	OS: Microsoft Windows NT 6.2.9200.0 (64bit: True)
[03/09/16 00:52:46] [Server API] Verbose: 	Mono: False
[03/09/16 00:52:47] [Server API] Info: Plugin TShock v4.3.9.0 (by The TShock Team) initiated.
[03/09/16 00:52:48] [Server API] Error: Server crashed due to an unhandled exception:
System.InvalidOperationException: Failed to compare two elements in the array. ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at Terraria.Main.WorldListSortMethod(WorldFileData data1, WorldFileData data2)
   at System.Array.FunctorComparer`1.Compare(T x, T y)
   at System.Collections.Generic.ArraySortHelper`1.InsertionSort(T[] keys, Int32 lo, Int32 hi, IComparer`1 comparer)
   at System.Collections.Generic.ArraySortHelper`1.IntroSort(T[] keys, Int32 lo, Int32 hi, Int32 depthLimit, IComparer`1 comparer)
   at System.Collections.Generic.ArraySortHelper`1.IntrospectiveSort(T[] keys, Int32 left, Int32 length, IComparer`1 comparer)
   at System.Collections.Generic.ArraySortHelper`1.Sort(T[] keys, Int32 index, Int32 length, IComparer`1 comparer)
   --- End of inner exception stack trace ---
   at System.Collections.Generic.ArraySortHelper`1.Sort(T[] keys, Int32 index, Int32 length, IComparer`1 comparer)
   at System.Array.Sort[T](T[] array, Int32 index, Int32 length, IComparer`1 comparer)
   at System.Collections.Generic.List`1.Sort(Comparison`1 comparison)
   at Terraria.Main.LoadWorlds()
   at Terraria.Main.DedServ()
   at Terraria.ProgramServer.InnerStart(String[] args)
[03/09/16 00:53:49] [Server API] Verbose: TerrariaApi - Server v1.21.0.0 started.
[03/09/16 00:53:49] [Server API] Verbose: 	Command line: TerrariaServer.exe  -config serverconfig.txt
[03/09/16 00:53:49] [Server API] Verbose: 	OS: Microsoft Windows NT 6.2.9200.0 (64bit: True)
[03/09/16 00:53:49] [Server API] Verbose: 	Mono: False
[03/09/16 00:53:49] [TShock] Verbose: Loading dedicated config file: serverconfig.txt
[03/09/16 00:53:50] [Server API] Info: Plugin TShock v4.3.9.0 (by The TShock Team) initiated.
[03/09/16 00:53:51] [Server API] Error: Server crashed due to an unhandled exception:
System.InvalidOperationException: Failed to compare two elements in the array. ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at Terraria.Main.WorldListSortMethod(WorldFileData data1, WorldFileData data2)
   at System.Array.FunctorComparer`1.Compare(T x, T y)
   at System.Collections.Generic.ArraySortHelper`1.InsertionSort(T[] keys, Int32 lo, Int32 hi, IComparer`1 comparer)
   at System.Collections.Generic.ArraySortHelper`1.IntroSort(T[] keys, Int32 lo, Int32 hi, Int32 depthLimit, IComparer`1 comparer)
   at System.Collections.Generic.ArraySortHelper`1.IntrospectiveSort(T[] keys, Int32 left, Int32 length, IComparer`1 comparer)
   at System.Collections.Generic.ArraySortHelper`1.Sort(T[] keys, Int32 index, Int32 length, IComparer`1 comparer)
   --- End of inner exception stack trace ---
   at System.Collections.Generic.ArraySortHelper`1.Sort(T[] keys, Int32 index, Int32 length, IComparer`1 comparer)
   at System.Array.Sort[T](T[] array, Int32 index, Int32 length, IComparer`1 comparer)
   at System.Collections.Generic.List`1.Sort(Comparison`1 comparison)
   at Terraria.Main.LoadWorlds()
   at Terraria.Main.DedServ()
   at Terraria.ProgramServer.InnerStart(String[] args)
[03/09/16 00:55:26] [Server API] Verbose: TerrariaApi - Server v1.21.0.0 started.
[03/09/16 00:55:26] [Server API] Verbose: 	Command line: TerrariaServer.exe  -config serverconfig.txt
[03/09/16 00:55:26] [Server API] Verbose: 	OS: Microsoft Windows NT 6.2.9200.0 (64bit: True)
[03/09/16 00:55:26] [Server API] Verbose: 	Mono: False
[03/09/16 00:55:26] [TShock] Verbose: Loading dedicated config file: serverconfig.txt
[03/09/16 00:55:27] [Server API] Info: Plugin TShock v4.3.9.0 (by The TShock Team) initiated.
[03/09/16 00:55:28] [Server API] Error: Server crashed due to an unhandled exception:
System.InvalidOperationException: Failed to compare two elements in the array. ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at Terraria.Main.WorldListSortMethod(WorldFileData data1, WorldFileData data2)
   at System.Array.FunctorComparer`1.Compare(T x, T y)
   at System.Collections.Generic.ArraySortHelper`1.InsertionSort(T[] keys, Int32 lo, Int32 hi, IComparer`1 comparer)
   at System.Collections.Generic.ArraySortHelper`1.IntroSort(T[] keys, Int32 lo, Int32 hi, Int32 depthLimit, IComparer`1 comparer)
   at System.Collections.Generic.ArraySortHelper`1.IntrospectiveSort(T[] keys, Int32 left, Int32 length, IComparer`1 comparer)
   at System.Collections.Generic.ArraySortHelper`1.Sort(T[] keys, Int32 index, Int32 length, IComparer`1 comparer)
   --- End of inner exception stack trace ---
   at System.Collections.Generic.ArraySortHelper`1.Sort(T[] keys, Int32 index, Int32 length, IComparer`1 comparer)
   at System.Array.Sort[T](T[] array, Int32 index, Int32 length, IComparer`1 comparer)
   at System.Collections.Generic.List`1.Sort(Comparison`1 comparison)
   at Terraria.Main.LoadWorlds()
   at Terraria.Main.DedServ()
   at Terraria.ProgramServer.InnerStart(String[] args)
[03/09/16 00:56:39] [Server API] Verbose: TerrariaApi - Server v1.21.0.0 started.
[03/09/16 00:56:39] [Server API] Verbose: 	Command line: "C:\Users\User\Desktop\TShock Server\TerrariaServer.exe" 
[03/09/16 00:56:39] [Server API] Verbose: 	OS: Microsoft Windows NT 6.2.9200.0 (64bit: True)
[03/09/16 00:56:39] [Server API] Verbose: 	Mono: False
[03/09/16 00:56:39] [Server API] Info: Plugin TShock v4.3.9.0 (by The TShock Team) initiated.
[03/09/16 00:56:40] [Server API] Error: Server crashed due to an unhandled exception:
System.InvalidOperationException: Failed to compare two elements in the array. ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at Terraria.Main.WorldListSortMethod(WorldFileData data1, WorldFileData data2)
   at System.Array.FunctorComparer`1.Compare(T x, T y)
   at System.Collections.Generic.ArraySortHelper`1.InsertionSort(T[] keys, Int32 lo, Int32 hi, IComparer`1 comparer)
   at System.Collections.Generic.ArraySortHelper`1.IntroSort(T[] keys, Int32 lo, Int32 hi, Int32 depthLimit, IComparer`1 comparer)
   at System.Collections.Generic.ArraySortHelper`1.IntrospectiveSort(T[] keys, Int32 left, Int32 length, IComparer`1 comparer)
   at System.Collections.Generic.ArraySortHelper`1.Sort(T[] keys, Int32 index, Int32 length, IComparer`1 comparer)
   --- End of inner exception stack trace ---
   at System.Collections.Generic.ArraySortHelper`1.Sort(T[] keys, Int32 index, Int32 length, IComparer`1 comparer)
   at System.Array.Sort[T](T[] array, Int32 index, Int32 length, IComparer`1 comparer)
   at System.Collections.Generic.List`1.Sort(Comparison`1 comparison)
   at Terraria.Main.LoadWorlds()
   at Terraria.Main.DedServ()
   at Terraria.ProgramServer.InnerStart(String[] args)
[03/09/16 00:58:24] [Server API] Verbose: TerrariaApi - Server v1.21.0.0 started.
[03/09/16 00:58:24] [Server API] Verbose: 	Command line: "C:\Users\User\Desktop\TShock Server\TerrariaServer.exe" 
[03/09/16 00:58:24] [Server API] Verbose: 	OS: Microsoft Windows NT 6.2.9200.0 (64bit: True)
[03/09/16 00:58:24] [Server API] Verbose: 	Mono: False
[03/09/16 00:58:24] [Server API] Info: Plugin TShock v4.3.9.0 (by The TShock Team) initiated.
[03/09/16 00:58:25] [Server API] Error: Server crashed due to an unhandled exception:
System.InvalidOperationException: Failed to compare two elements in the array. ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at Terraria.Main.WorldListSortMethod(WorldFileData data1, WorldFileData data2)
   at System.Array.FunctorComparer`1.Compare(T x, T y)
   at System.Collections.Generic.ArraySortHelper`1.InsertionSort(T[] keys, Int32 lo, Int32 hi, IComparer`1 comparer)
   at System.Collections.Generic.ArraySortHelper`1.IntroSort(T[] keys, Int32 lo, Int32 hi, Int32 depthLimit, IComparer`1 comparer)
   at System.Collections.Generic.ArraySortHelper`1.IntrospectiveSort(T[] keys, Int32 left, Int32 length, IComparer`1 comparer)
   at System.Collections.Generic.ArraySortHelper`1.Sort(T[] keys, Int32 index, Int32 length, IComparer`1 comparer)
   --- End of inner exception stack trace ---
   at System.Collections.Generic.ArraySortHelper`1.Sort(T[] keys, Int32 index, Int32 length, IComparer`1 comparer)
   at System.Array.Sort[T](T[] array, Int32 index, Int32 length, IComparer`1 comparer)
   at System.Collections.Generic.List`1.Sort(Comparison`1 comparison)
   at Terraria.Main.LoadWorlds()
   at Terraria.Main.DedServ()
   at Terraria.ProgramServer.InnerStart(String[] args)
[03/09/16 00:58:44] [Server API] Verbose: TerrariaApi - Server v1.21.0.0 started.
[03/09/16 00:58:44] [Server API] Verbose: 	Command line: "C:\Users\User\Desktop\TShock Server\TerrariaServer.exe" 
[03/09/16 00:58:44] [Server API] Verbose: 	OS: Microsoft Windows NT 6.2.9200.0 (64bit: True)
[03/09/16 00:58:44] [Server API] Verbose: 	Mono: False
[03/09/16 00:58:44] [Server API] Info: Plugin TShock v4.3.9.0 (by The TShock Team) initiated.
[03/09/16 00:58:46] [Server API] Error: Server crashed due to an unhandled exception:
System.InvalidOperationException: Failed to compare two elements in the array. ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at Terraria.Main.WorldListSortMethod(WorldFileData data1, WorldFileData data2)
   at System.Array.FunctorComparer`1.Compare(T x, T y)
   at System.Collections.Generic.ArraySortHelper`1.InsertionSort(T[] keys, Int32 lo, Int32 hi, IComparer`1 comparer)
   at System.Collections.Generic.ArraySortHelper`1.IntroSort(T[] keys, Int32 lo, Int32 hi, Int32 depthLimit, IComparer`1 comparer)
   at System.Collections.Generic.ArraySortHelper`1.IntrospectiveSort(T[] keys, Int32 left, Int32 length, IComparer`1 comparer)
   at System.Collections.Generic.ArraySortHelper`1.Sort(T[] keys, Int32 index, Int32 length, IComparer`1 comparer)
   --- End of inner exception stack trace ---
   at System.Collections.Generic.ArraySortHelper`1.Sort(T[] keys, Int32 index, Int32 length, IComparer`1 comparer)
   at System.Array.Sort[T](T[] array, Int32 index, Int32 length, IComparer`1 comparer)
   at System.Collections.Generic.List`1.Sort(Comparison`1 comparison)
   at Terraria.Main.LoadWorlds()
   at Terraria.Main.DedServ()
   at Terraria.ProgramServer.InnerStart(String[] args)
[03/09/16 01:00:03] [Server API] Verbose: TerrariaApi - Server v1.22.0.0 started.
[03/09/16 01:00:03] [Server API] Verbose: 	Command line: "C:\Users\User\Desktop\TShock Server\TerrariaServer.exe" 
[03/09/16 01:00:03] [Server API] Verbose: 	OS: Microsoft Windows NT 6.2.9200.0 (64bit: True)
[03/09/16 01:00:03] [Server API] Verbose: 	Mono: False
[03/09/16 01:00:03] [Server API] Info: Plugin TShock v4.3.12.0 (by The TShock Team) initiated.
[03/09/16 01:00:04] [Server API] Error: Server crashed due to an unhandled exception:
System.InvalidOperationException: Failed to compare two elements in the array. ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at Terraria.Main.WorldListSortMethod(WorldFileData data1, WorldFileData data2)
   at System.Array.FunctorComparer`1.Compare(T x, T y)
   at System.Collections.Generic.ArraySortHelper`1.InsertionSort(T[] keys, Int32 lo, Int32 hi, IComparer`1 comparer)
   at System.Collections.Generic.ArraySortHelper`1.IntroSort(T[] keys, Int32 lo, Int32 hi, Int32 depthLimit, IComparer`1 comparer)
   at System.Collections.Generic.ArraySortHelper`1.IntrospectiveSort(T[] keys, Int32 left, Int32 length, IComparer`1 comparer)
   at System.Collections.Generic.ArraySortHelper`1.Sort(T[] keys, Int32 index, Int32 length, IComparer`1 comparer)
   --- End of inner exception stack trace ---
   at System.Collections.Generic.ArraySortHelper`1.Sort(T[] keys, Int32 index, Int32 length, IComparer`1 comparer)
   at System.Array.Sort[T](T[] array, Int32 index, Int32 length, IComparer`1 comparer)
   at System.Collections.Generic.List`1.Sort(Comparison`1 comparison)
   at Terraria.Main.LoadWorlds()
   at Terraria.Main.DedServ()
   at Terraria.ProgramServer.InnerStart(String[] args)
[03/09/16 01:04:56] [Server API] Verbose: TerrariaApi - Server v1.22.0.0 started.
[03/09/16 01:04:56] [Server API] Verbose: 	Command line: "C:\Users\User\Desktop\TShock Server\TerrariaServer.exe" 
[03/09/16 01:04:56] [Server API] Verbose: 	OS: Microsoft Windows NT 6.2.9200.0 (64bit: True)
[03/09/16 01:04:56] [Server API] Verbose: 	Mono: False
[03/09/16 01:05:02] [Server API] Info: Plugin TShock v4.3.12.0 (by The TShock Team) initiated.
[03/09/16 01:05:06] [Server API] Error: Server crashed due to an unhandled exception:
System.InvalidOperationException: Failed to compare two elements in the array. ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at Terraria.Main.WorldListSortMethod(WorldFileData data1, WorldFileData data2)
   at System.Array.FunctorComparer`1.Compare(T x, T y)
   at System.Collections.Generic.ArraySortHelper`1.InsertionSort(T[] keys, Int32 lo, Int32 hi, IComparer`1 comparer)
   at System.Collections.Generic.ArraySortHelper`1.IntroSort(T[] keys, Int32 lo, Int32 hi, Int32 depthLimit, IComparer`1 comparer)
   at System.Collections.Generic.ArraySortHelper`1.IntrospectiveSort(T[] keys, Int32 left, Int32 length, IComparer`1 comparer)
   at System.Collections.Generic.ArraySortHelper`1.Sort(T[] keys, Int32 index, Int32 length, IComparer`1 comparer)
   --- End of inner exception stack trace ---
   at System.Collections.Generic.ArraySortHelper`1.Sort(T[] keys, Int32 index, Int32 length, IComparer`1 comparer)
   at System.Array.Sort[T](T[] array, Int32 index, Int32 length, IComparer`1 comparer)
   at System.Collections.Generic.List`1.Sort(Comparison`1 comparison)
   at Terraria.Main.LoadWorlds()
   at Terraria.Main.DedServ()
   at Terraria.ProgramServer.InnerStart(String[] args)
`
`

I'ma newbie on programming so i literally have no idea what it is, please help! Thanks in advance :)

**Comment by nicatronTg** [comment]
https://tshock.co/xf/index.php?threads/ultimate-guide-how-to-get-help-common-quick-fixes.3857/

See the second bullet.

**Comment by mnassassin** [comment]
Thank you!
