### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by CodingKuda** [NyxStudios/TShock#1184]
Hi im new to TSHOCK.
When i run tshock v1.3.0.5
I get this error: 
[Server API] Error Server crashed due to an unhandled exception:
System.ArgumentNullException: Value cannot be null.
Parameter name: path
   at System.IO.Path.GetFullPathInternal(String path)
   at System.IO.File.InternalGetLastWriteTimeUtc(String path, Boolean checkHost)
   at System.IO.File.GetLastWriteTime(String path)
   at Terraria.Main.DedServ()
   at Terraria.ProgramServer.InnerStart(String[] args)
PLEASE help.

**Comment by WhiteXZ** [comment]
Remove your worlds from the world folder.
Re-Add them one at a time until this issue reoccurs.
Open the broken world in Terraria singleplayer or a map editor such as TEdit.
Save the world

**Comment by CodingKuda** [comment]
OK thanks.
