### ISSUE TITLE
TShock crashing on start (Terraria 1.3.1)

### ISSUE THREAD

**Issue by MakeLord** [NyxStudios/TShock#1186]
After Terraria 1.3.1 update, TShock crashes at startup.

ServerLog: 
`[05.24.16 18:34:03] [Server API] Verbose: TerrariaApi - Server v1.22.0.0 started.
[05.24.16 18:34:03] [Server API] Verbose: 	Command line: "C:\Users\Make\Documents\Pelit\Terraria\TShock\TerrariaServer.exe" 
[05.24.16 18:34:03] [Server API] Verbose: 	OS: Microsoft Windows NT 6.1.7601 Service Pack 1 (64bit: True)
[05.24.16 18:34:03] [Server API] Verbose: 	Mono: False
[05.24.16 18:34:03] [Server API] Info: Plugin TShock v4.3.13.0 (by The TShock Team) initiated.
[05.24.16 18:34:05] [Server API] Error: Server crashed due to an unhandled exception:
System.ArgumentNullException: Value cannot be null.
Parameter name: path
   at System.IO.Path.GetFullPathInternal(String path)
   at System.IO.File.InternalGetLastWriteTimeUtc(String path, Boolean checkHost)
   at System.IO.File.GetLastWriteTime(String path)
   at Terraria.Main.DedServ()
   at Terraria.ProgramServer.InnerStart(String[] args)
`

How to reproduce the issue:
1. Update Terraria to 1.3.1
2. Try to start TShock version 4.3.13
3. Crash...

TShock version: 4.3.13 (Latest)

**Comment by WhiteXZ** [comment]
TShock 4.3.13 does not support Terraria 1.3.1
