### ISSUE TITLE
I smell something very bad with these ID's..

### ISSUE THREAD

**Issue by tlworks** [NyxStudios/TShock#1207]
2016-06-03 19:42:34 - Utils: INFO: OFF executed: /itemban add 3706.
2016-06-03 19:42:35 - ItemManager: ERROR: MySql.Data.MySqlClient.MySqlException (0x80004005): Duplicate entry 'Platinum Bow' for key 'PRIMARY'
   at MySql.Data.MySqlClient.MySqlStream.ReadPacket()
   at MySql.Data.MySqlClient.NativeDriver.GetResult(Int32& affectedRow, Int64& insertedId)
   at MySql.Data.MySqlClient.Driver.GetResult(Int32 statementId, Int32& affectedRows, Int64& insertedId)
   at MySql.Data.MySqlClient.Driver.NextResult(Int32 statementId, Boolean force)
   at MySql.Data.MySqlClient.MySqlDataReader.NextResult()
   at MySql.Data.MySqlClient.MySqlCommand.ExecuteReader(CommandBehavior behavior)
   at MySql.Data.MySqlClient.MySqlCommand.ExecuteNonQuery()
   at TShockAPI.DB.DbExt.Query(IDbConnection olddb, String query, Object[] args)
   at TShockAPI.DB.ItemManager.AddNewBan(String itemname)

Should I consider even banning these?

**Comment by tlworks** [comment]
Considering the fact the server things the item is a platinum bow.

**Comment by Enerdy** [comment]
https://github.com/NyxStudios/TerrariaAPI-Server/blob/general-devel/Terraria/ID/ItemID.cs#L7429
That's certainly weird. In our code base that's a fake chest.

**Comment by Enerdy** [comment]
https://dl.dropboxusercontent.com/u/31979270/screenshots/sbplanet.co_-_Remote_Desktop_Connection_2016-06-04_02-19-20.png

**Comment by tlworks** [comment]
@Enerdy I noticed upon having the Chestroom plugin and editing the source to add up to every ID, opening the last chest in the Chestroom will show those two items as blueberry seeds and seaweed but if you try to place them nothing happens (apart from showing a chest which doesn't exist in Terraria yet, a whole new kind of chest) and it somehow slightly changes your armor look upon trying to place it.

**Comment by WhiteXZ** [comment]
These items are broken and can no longer be placed in a TShock server.
