### ISSUE TITLE
Server Deadlock by corrupt packet. (List of packets that must be fixed).

### ISSUE THREAD

**Issue by tlworks** [NyxStudios/TShock#1208]
Only seems to happen on non-SSC as this packet error never seems to occur on any of my other Servers running.

http://pastebin.com/uiG98TcS

Could someone enlighten me on this, if this is actually a TShock issue?

**Comment by tlworks** [comment]
Not forget this one;

`[06/03/16 17:09:46] [Server API] Warning: Packet contents: [44 00]
[06/03/16 17:17:39] [Server API] Warning: Server could not process a packet because it was corrupt.
[06/03/16 17:17:39] [Server API] Warning: System.OverflowException: Arithmetic operation resulted in an overflow.
   at TerrariaApi.Server.HookManager.InvokeNetGetData(Byte& msgId, MessageBuffer buffer, Int32& index, Int32& length)
   at Terraria.MessageBuffer.GetData(Int32 start, Int32 length)
   at Terraria.NetMessage.CheckBytes(Int32 bufferIndex)`

**Comment by tlworks** [comment]
If anyone knows the issue to the pastebin log above, please do share as I wish to get rid of Server deadlocks.

Thanks in advance!

**Comment by tlworks** [comment]
[06/15/16 02:34:54] [Server API] Warning: Server could not process a packet because it was corrupt.
[06/15/16 02:34:54] [Server API] Warning: System.OverflowException: Arithmetic operation resulted in an overflow.
   at TerrariaApi.Server.HookManager.InvokeNetGetData(Byte& msgId, MessageBuffer buffer, Int32& index, Int32& length)
   at Terraria.MessageBuffer.GetData(Int32 start, Int32 length)
   at Terraria.NetMessage.CheckBytes(Int32 bufferIndex)
[06/15/16 02:34:54] [Server API] Warning: Packet contents: [44 01 38]

**Comment by nicatronTg** [comment]
Alright @NyxStudios/tshock what's the status on this issue?

**Comment by nicatronTg** [comment]
_I've assigned myself to this issue for monitoring, however, I'm not actively working this issue._

**Comment by Patrikkk** [comment]
I've not ran into any deadlocks lately. Especially not those kinds of error messages. 
I think it is safe to close this. 

(I've ran into a completely unrelated, different error which I'm looking into)
