### ISSUE TITLE
Wiring Exception, DoubleStack is empty.

### ISSUE THREAD

**Issue by tlworks** [NyxStudios/TShock#1211]
[06/08/16 06:38:12] [Server API] Warning: System.InvalidOperationException: The DoubleStack is empty.
   at Terraria.DataStructures.DoubleStack`1.PopFront()
   at Terraria.Wiring.HitWire(DoubleStack`1 next, Int32 wireType)
   at Terraria.Wiring.TripWire(Int32 left, Int32 top, Int32 width, Int32 height)
   at Terraria.Wiring.HitSwitch(Int32 i, Int32 j)
   at Terraria.MessageBuffer.GetData(Int32 start, Int32 length)
   at Terraria.NetMessage.CheckBytes(Int32 bufferIndex)
[06/08/16 06:38:12] [Server API] Warning: Packet contents: [3B DF 0A A8 04]

Using the latest TShock Bamboo (The one which contains Tyler's Wiring Deadlock fix), reason why it happens is unknown. Error comes from ServerLog.txt

**Comment by WhiteXZ** [comment]
Fixed in https://github.com/NyxStudios/TerrariaAPI-Server/pull/58
