### ISSUE TITLE
Please tell me how to fix this Thanks:)

### ISSUE THREAD

**Issue by ramadhaaana** [NyxStudios/TShock#1238]
2016-07-11 20:48:27 - TextLog: INFO: TShock 4.3.16.0 (Yoraiz0r R0cks) now running.
2016-07-11 20:48:27 - TShock: INFO: AutoSave Enabled
2016-07-11 20:48:27 - TShock: INFO: Backups Disabled
2016-07-11 20:48:27 - TShock: INFO: Welcome to TShock for Terraria. Initialization complete.
2016-07-11 20:48:53 - TShock: ERROR: System.IO.IOException: Data error (cyclic redundancy check).

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.ReadCore(Byte[] buffer, Int32 offset, Int32 count)
   at System.IO.FileStream.Read(Byte[] array, Int32 offset, Int32 count)
   at System.IO.File.InternalReadAllBytes(String path, Boolean checkHost)
   at Terraria.Utilities.FileUtilities.ReadAllBytes(String path)
   at Terraria.IO.WorldFile.loadWorld()
   at Terraria.WorldGen.serverLoadWorldCallBack(Object threadContext)
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart(Object obj)
2016-07-11 20:48:53 - Utils: INFO: Broadcast: Saving world. Momentary lag might result from this.
2016-07-11 20:48:53 - SaveManager: ERROR: World saved failed
2016-07-11 20:48:53 - SaveManager: ERROR: System.NullReferenceException: Object reference not set to an instance of an object.
   at Terraria.IO.WorldFile.SaveFileFormatHeader(BinaryWriter writer)
   at Terraria.IO.WorldFile.SaveWorld_Version2(BinaryWriter writer)
   at Terraria.IO.WorldFile.saveWorld(Boolean resetTime)
   at TShockAPI.SaveManager.SaveWorker()

**Comment by tlworks** [comment]
All I can think of is a corrupted world, unless this happens on every world you have.

**Comment by Ijwu** [comment]
Corrupted world.

Troubleshooting and error support should be directed to the TShock forums, rather than posted as GitHub issues. 

Try loading a backup of your world. Also try with other worlds. If only this world fails to load then you have a corrupted world, tough luck. If all worlds fail to load then you should post a thread on our forums about this.

**Comment by tylerjwatson** [comment]
As a footnote to your issue, CRC errors are filesystem related. It means the filesystem entry in your filesystems metadata doesn't match the file and your system is in quite a lot of danger of corruption if not fixed.

Re-logic world files do not have any data integrity checks built into them (apart from a magic), and cannot check themselves for consistency. 

It would be pertinent to do a `chkdsk /f` as soon as possible.
