### ISSUE TITLE
Crash at Launch, Terraria v 1.3.2

### ISSUE THREAD

**Issue by Daygall** [NyxStudios/TShock#1246]
[Server API] Error Server crashed due to an unhandled exception:
System.InvalidOperationException: Failed to compare two elements in the array. ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at Terraria.Main.WorldListSortMethod(WorldFileData data1, WorldFileData data2)
   at System.Array.FunctorComparer`1.Compare(T x, T y)
   at System.Collections.Generic.ArraySortHelper`1.SwapIfGreater(T[] keys, IComparer`1 comparer, Int32 a, Int32 b)
   at System.Collections.Generic.ArraySortHelper`1.IntroSort(T[] keys, Int32 lo, Int32 hi, Int32 depthLimit, IComparer`1 comparer)
   at System.Collections.Generic.ArraySortHelper`1.IntrospectiveSort(T[] keys, Int32 left, Int32 length, IComparer`1 comparer)
   at System.Collections.Generic.ArraySortHelper`1.Sort(T[] keys, Int32 index, Int32 length, IComparer`1 comparer)
   --- End of inner exception stack trace ---
   at System.Collections.Generic.ArraySortHelper`1.Sort(T[] keys, Int32 index, Int32 length, IComparer`1 comparer)
   at System.Array.Sort[T](T[] array, Int32 index, Int32 length, IComparer`1 comparer)
   at System.Collections.Generic.List`1.Sort(Comparison`1 comparison)
   at Terraria.Main.LoadWorlds()
   at Terraria.Main.DedServ()
   at Terraria.ProgramServer.InnerStart(String[] args)

**Comment by mistzzt** [comment]
This was caused by map files in newer version.
You can avoid this error by moving these map files to other directories.

**Comment by ProfessorXZ** [comment]
#1245 Duplicate. Both issues should be closed because this was covered in the Ultimate Guide on the forums.
