### ISSUE TITLE
This Comes up when I start the server, please help me

### ISSUE THREAD

**Issue by Thevin** [NyxStudios/TShock#1273]
`2016-08-15 11:18:10 - TextLog: ERROR: UpdateManager Exception: System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: No connection could be made because the target machine actively refused it 104.28.26.122:80
   at System.Net.Sockets.Socket.DoConnect(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)
   --- End of inner exception stack trace ---
   at System.Net.HttpWebRequest.GetResponse()
   at TShockAPI.Utils.GetResponseNoException(HttpWebRequest req)
   at TShockAPI.UpdateManager.ServerIsOutOfDate()`

**Comment by Thevin** [comment]
im sorry im new to tshock and this makes me worry

**Comment by tlworks** [comment]
It says exactly what the issue is. No connection could be made to the defined host (which in this case is the UpdateManager checking the current TShock version).

It's not really an issue.

**Comment by Thevin** [comment]
so i just have to ignore it?

**Comment by tlworks** [comment]
Yes because the UpdataManager is useless anyway.
