### ISSUE TITLE
Errors generated on startup with "StorageType": "sqlite", and "UseSqlLogs": true

### ISSUE THREAD

**Issue by Grandpa-G** [NyxStudios/TShock#892]
I set  "StorageType": "sqlite", and also   "UseSqlLogs": true, when starting the server I got a number of messages like:
````
2015-03-23 08:27:47 - TextLog: ERROR: SQL Log insert query failed: Mono.Data.Sqlite.SqliteException (0x80004005): SQLite error
no such table: Logs
   at Mono.Data.Sqlite.SQLite3.Prepare(SqliteConnection cnn, String strSql, SqliteStatement previous, UInt32 timeoutMS, String& strRemain)
   at Mono.Data.Sqlite.SqliteCommand.BuildNextCommand()
   at Mono.Data.Sqlite.SqliteCommand.GetStatement(Int32 index)
   at Mono.Data.Sqlite.SqliteDataReader.NextResult()
   at Mono.Data.Sqlite.SqliteDataReader..ctor(SqliteCommand cmd, CommandBehavior behave)
   at Mono.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
   at Mono.Data.Sqlite.SqliteCommand.ExecuteNonQuery()
   at TShockAPI.DB.DbExt.Query(IDbConnection olddb, String query, Object[] args)
   at TShockAPI.SqlLog.Write(String message, LogLevel level)
````

**Comment by nicatronTg** [comment]
This is a known issue, and is being tracked in the pull request #891.
