### ISSUE TITLE
Server Side Character Issues

### ISSUE THREAD

**Issue by Puremin0rez** [NyxStudios/TShock#952]
The trash slot is not wiped upon connecting to a server side character enabled server, making it so people can leave something in their trash slot, connect to a server and then take it out once logged in.

Piggy Banks, Safes and Money Troughs have a "infinite" problem in which you can take things out of them, relog, and the items will still be in them and in your inventory also.

**Comment by WhiteXZ** [comment]
This is a known issue - I didn't fully update the SSC system to support the new access we have to piggy banks, etc.
This will be fixed sometime in the next few days

**Comment by madfunny** [comment]
Thanks WhiteXZ,
I can also confirm, have this same issue, people have all or some of their things in the safe/piggybank when they join SSC

**Comment by Puremin0rez** [comment]
Just adding to this issue that item modifiers are also broken with SSC. They get wiped when relogging.

**Comment by WhiteXZ** [comment]
Merging SSC issues into one location. https://github.com/NyxStudios/TShock/issues/963

**Comment by Fireboss** [comment]
can any one help me i need to run this tshock server
[07/07/15 06:31:39] [Server API] Verbose: TerrariaApi - Server v1.18.0.0 started.
[07/07/15 06:31:39] [Server API] Verbose:     Command line: "C:\Users\Administrator\Desktop\tShock\TerrariaServer.exe"
[07/07/15 06:31:39] [Server API] Verbose:     OS: Microsoft Windows NT 6.1.7600.0 (64bit: True)
[07/07/15 06:31:39] [Server API] Verbose:     Mono: False
[07/07/15 06:31:40] [Server API] Error: Startup aborted due to an exception in the Server API initialization:
System.InvalidOperationException: Plugin "TShock" has thrown an exception during initialization. ---> System.Exception: Fatal TShock initialization exception. See inner exception for details. ---> System.TypeLoadException: Could not load type 'System.Collections.Generic.IReadOnlyDictionary`2' from assembly 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'.
   at Newtonsoft.Json.Utilities.CollectionUtils.IsDictionaryType(Type type)
   at Newtonsoft.Json.Serialization.DefaultContractResolver.CreateContract(Type objectType)
   at Newtonsoft.Json.Serialization.DefaultContractResolver.ResolveContract(Type type)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.Serialize(JsonWriter jsonWriter, Object value, Type objectType)
   at Newtonsoft.Json.JsonSerializer.SerializeInternal(JsonWriter jsonWriter, Object value, Type objectType)
   at Newtonsoft.Json.JsonConvert.SerializeObjectInternal(Object value, Type type, JsonSerializer jsonSerializer)
   at TShockAPI.ConfigFile.Write(Stream stream)
   at TShockAPI.ConfigFile.Write(String path)
   at TShockAPI.FileTools.SetupConfig()
   at TShockAPI.TShock.Initialize()
   --- End of inner exception stack trace ---
   at TShockAPI.TShock.Initialize()
   at TerrariaApi.Server.ServerApi.LoadPlugins()
   --- End of inner exception stack trace ---
   at TerrariaApi.Server.ServerApi.LoadPlugins()
   at TerrariaApi.Server.ServerApi.Initialize(String[] commandLineArgs, Main game)
   at Terraria.ProgramServer.InnerStart(String[] args)

**Comment by WhiteXZ** [comment]
Please read the forums.
