### ISSUE TITLE
/buff causes Command failed, check logs for more details when using an invalid name

### ISSUE THREAD

**Issue by ancientgods** [NyxStudios/TShock#955]

**Comment by WhiteXZ** [comment]
What do the logs say?

**Comment by ancientgods** [comment]
2015-07-06 19:03:36 - Utils: INFO: Ancientgods executed: /buff derp.
2015-07-06 19:03:36 - Command: ERROR: System.NullReferenceException: Object reference not set to an instance of an object.
   at TShockAPI.Utils.GetBuffByName(String name)
   at TShockAPI.Commands.Buff(CommandArgs args)
   at TShockAPI.Command.Run(String msg, Boolean silent, TSPlayer ply, List`1 parms)

**Comment by Etherealflux** [comment]
Could there be a null entry in the buffName array? I'm not sure where it's declared and I can't test anything for the next few hours, but it seems like the only way you could get a null pointer exception in the GetBuffByName method.

Valid names would be found before hitting the end of the array, so the issue would be masked.

**Comment by Enerdy** [comment]
fd96f9d65c8eb478e888c8326a2a9b47b70038fd closes this.

**Comment by Etherealflux** [comment]
Ah, makes sense. Was puzzled by how a null was slipping through.
