### ISSUE TITLE
Server crashes after startup but copied files to my other pc works fine?

### ISSUE THREAD

**Issue by wrentrillogy** [NyxStudios/TShock#959]
[07/06/15 16:00:50] [Server API] Verbose: TerrariaApi - Server v1.18.0.0 started.
[07/06/15 16:00:50] [Server API] Verbose: 	Command line: "C:\Users\Server\Desktop\Tshock Terraria Server\TerrariaServer.exe" 
[07/06/15 16:00:50] [Server API] Verbose: 	OS: Microsoft Windows NT 6.1.7601 Service Pack 1 (64bit: True)
[07/06/15 16:00:50] [Server API] Verbose: 	Mono: False
[07/06/15 16:00:51] [Server API] Error: Startup aborted due to an exception in the Server API initialization:
System.InvalidOperationException: Plugin "TShock" has thrown an exception during initialization. ---> System.Exception: Fatal TShock initialization exception. See inner exception for details. ---> System.TypeLoadException: Could not load type 'System.Collections.Generic.IReadOnlyDictionary`2' from assembly 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'.
   at Newtonsoft.Json.Utilities.CollectionUtils.IsDictionaryType(Type type)
   at Newtonsoft.Json.Serialization.DefaultContractResolver.CreateContract(Type objectType)
   at Newtonsoft.Json.Serialization.DefaultContractResolver.ResolveContract(Type type)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.Serialize(JsonWriter jsonWriter, Object value, Type objectType)
   at Newtonsoft.Json.JsonSerializer.SerializeInternal(JsonWriter jsonWriter, Object value, Type objectType)
   at Newtonsoft.Json.JsonConvert.SerializeObjectInternal(Object value, Type type, JsonSerializer jsonSerializer)
   at TShockAPI.ConfigFile.Write(Stream stream)
   at TShockAPI.ConfigFile.Write(String path)
   at TShockAPI.FileTools.SetupConfig()
   at TShockAPI.TShock.Initialize()
   --- End of inner exception stack trace ---
   at TShockAPI.TShock.Initialize()
   at TerrariaApi.Server.ServerApi.LoadPlugins()
   --- End of inner exception stack trace ---
   at TerrariaApi.Server.ServerApi.LoadPlugins()
   at TerrariaApi.Server.ServerApi.Initialize(String[] commandLineArgs, Main game)
   at Terraria.ProgramServer.InnerStart(String[] args)
[07/06/15 16:01:07] [Server API] Verbose: TerrariaApi - Server v1.18.0.0 started.
[07/06/15 16:01:07] [Server API] Verbose: 	Command line: "C:\Users\Server\Desktop\Tshock Terraria Server\TerrariaServer.exe" 
[07/06/15 16:01:07] [Server API] Verbose: 	OS: Microsoft Windows NT 6.1.7601 Service Pack 1 (64bit: True)
[07/06/15 16:01:07] [Server API] Verbose: 	Mono: False
[07/06/15 16:01:07] [Server API] Error: Startup aborted due to an exception in the Server API initialization:
System.InvalidOperationException: Plugin "TShock" has thrown an exception during initialization. ---> System.Exception: Fatal TShock initialization exception. See inner exception for details. ---> System.TypeLoadException: Could not load type 'System.Collections.Generic.IReadOnlyDictionary`2' from assembly 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'.
   at Newtonsoft.Json.Utilities.CollectionUtils.IsDictionaryType(Type type)
   at Newtonsoft.Json.Serialization.DefaultContractResolver.CreateContract(Type objectType)
   at Newtonsoft.Json.Serialization.DefaultContractResolver.ResolveContract(Type type)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at TShockAPI.ConfigFile.Read(Stream stream)
   at TShockAPI.ConfigFile.Read(String path)
   at TShockAPI.FileTools.SetupConfig()
   at TShockAPI.TShock.Initialize()
   --- End of inner exception stack trace ---
   at TShockAPI.TShock.Initialize()
   at TerrariaApi.Server.ServerApi.LoadPlugins()
   --- End of inner exception stack trace ---
   at TerrariaApi.Server.ServerApi.LoadPlugins()
   at TerrariaApi.Server.ServerApi.Initialize(String[] commandLineArgs, Main game)
   at Terraria.ProgramServer.InnerStart(String[] args)
[07/06/15 16:05:39] [Server API] Verbose: TerrariaApi - Server v1.18.0.0 started.
[07/06/15 16:05:39] [Server API] Verbose: 	Command line: "C:\Users\Server\Desktop\Tshock Terraria Server\TerrariaServer.exe" 
[07/06/15 16:05:39] [Server API] Verbose: 	OS: Microsoft Windows NT 6.1.7601 Service Pack 1 (64bit: True)
[07/06/15 16:05:39] [Server API] Verbose: 	Mono: False
[07/06/15 16:05:40] [Server API] Error: Startup aborted due to an exception in the Server API initialization:
System.InvalidOperationException: Plugin "TShock" has thrown an exception during initialization. ---> System.Exception: Fatal TShock initialization exception. See inner exception for details. ---> System.TypeLoadException: Could not load type 'System.Collections.Generic.IReadOnlyDictionary`2' from assembly 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'.
   at Newtonsoft.Json.Utilities.CollectionUtils.IsDictionaryType(Type type)
   at Newtonsoft.Json.Serialization.DefaultContractResolver.CreateContract(Type objectType)
   at Newtonsoft.Json.Serialization.DefaultContractResolver.ResolveContract(Type type)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at TShockAPI.ConfigFile.Read(Stream stream)
   at TShockAPI.ConfigFile.Read(String path)
   at TShockAPI.FileTools.SetupConfig()
   at TShockAPI.TShock.Initialize()
   --- End of inner exception stack trace ---
   at TShockAPI.TShock.Initialize()
   at TerrariaApi.Server.ServerApi.LoadPlugins()
   --- End of inner exception stack trace ---
   at TerrariaApi.Server.ServerApi.LoadPlugins()
   at TerrariaApi.Server.ServerApi.Initialize(String[] commandLineArgs, Main game)
   at Terraria.ProgramServer.InnerStart(String[] args)
[07/06/15 16:06:12] [Server API] Verbose: TerrariaApi - Server v1.18.0.0 started.
[07/06/15 16:06:12] [Server API] Verbose: 	Command line: "C:\Users\Server\Desktop\Tshock Terraria Server\TerrariaServer.exe" 
[07/06/15 16:06:12] [Server API] Verbose: 	OS: Microsoft Windows NT 6.1.7601 Service Pack 1 (64bit: True)
[07/06/15 16:06:12] [Server API] Verbose: 	Mono: False
[07/06/15 16:06:12] [Server API] Error: Startup aborted due to an exception in the Server API initialization:
System.InvalidOperationException: Plugin "TShock" has thrown an exception during initialization. ---> System.Exception: Fatal TShock initialization exception. See inner exception for details. ---> System.TypeLoadException: Could not load type 'System.Collections.Generic.IReadOnlyDictionary`2' from assembly 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'.
   at Newtonsoft.Json.Utilities.CollectionUtils.IsDictionaryType(Type type)
   at Newtonsoft.Json.Serialization.DefaultContractResolver.CreateContract(Type objectType)
   at Newtonsoft.Json.Serialization.DefaultContractResolver.ResolveContract(Type type)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at TShockAPI.ConfigFile.Read(Stream stream)
   at TShockAPI.ConfigFile.Read(String path)
   at TShockAPI.FileTools.SetupConfig()
   at TShockAPI.TShock.Initialize()
   --- End of inner exception stack trace ---
   at TShockAPI.TShock.Initialize()
   at TerrariaApi.Server.ServerApi.LoadPlugins()
   --- End of inner exception stack trace ---
   at TerrariaApi.Server.ServerApi.LoadPlugins()
   at TerrariaApi.Server.ServerApi.Initialize(String[] commandLineArgs, Main game)
   at Terraria.ProgramServer.InnerStart(String[] args)
[07/06/15 16:06:23] [Server API] Verbose: TerrariaApi - Server v1.18.0.0 started.
[07/06/15 16:06:23] [Server API] Verbose: 	Command line: "C:\Users\Server\Desktop\Tshock Terraria Server\TerrariaServer.exe" 
[07/06/15 16:06:23] [Server API] Verbose: 	OS: Microsoft Windows NT 6.1.7601 Service Pack 1 (64bit: True)
[07/06/15 16:06:23] [Server API] Verbose: 	Mono: False
[07/06/15 16:06:23] [Server API] Error: Startup aborted due to an exception in the Server API initialization:
System.InvalidOperationException: Plugin "TShock" has thrown an exception during initialization. ---> System.Exception: Fatal TShock initialization exception. See inner exception for details. ---> System.TypeLoadException: Could not load type 'System.Collections.Generic.IReadOnlyDictionary`2' from assembly 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'.
   at Newtonsoft.Json.Utilities.CollectionUtils.IsDictionaryType(Type type)
   at Newtonsoft.Json.Serialization.DefaultContractResolver.CreateContract(Type objectType)
   at Newtonsoft.Json.Serialization.DefaultContractResolver.ResolveContract(Type type)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at TShockAPI.ConfigFile.Read(Stream stream)
   at TShockAPI.ConfigFile.Read(String path)
   at TShockAPI.FileTools.SetupConfig()
   at TShockAPI.TShock.Initialize()
   --- End of inner exception stack trace ---
   at TShockAPI.TShock.Initialize()
   at TerrariaApi.Server.ServerApi.LoadPlugins()
   --- End of inner exception stack trace ---
   at TerrariaApi.Server.ServerApi.LoadPlugins()
   at TerrariaApi.Server.ServerApi.Initialize(String[] commandLineArgs, Main game)
   at Terraria.ProgramServer.InnerStart(String[] args)
[07/06/15 16:06:41] [Server API] Verbose: TerrariaApi - Server v1.18.0.0 started.
[07/06/15 16:06:41] [Server API] Verbose: 	Command line: "C:\Users\Server\Desktop\Tshock Terraria Server\TerrariaServer.exe" 
[07/06/15 16:06:41] [Server API] Verbose: 	OS: Microsoft Windows NT 6.1.7601 Service Pack 1 (64bit: True)
[07/06/15 16:06:41] [Server API] Verbose: 	Mono: False
[07/06/15 16:06:41] [Server API] Error: Startup aborted due to an exception in the Server API initialization:
System.InvalidOperationException: Plugin "TShock" has thrown an exception during initialization. ---> System.Exception: Fatal TShock initialization exception. See inner exception for details. ---> System.TypeLoadException: Could not load type 'System.Collections.Generic.IReadOnlyDictionary`2' from assembly 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'.
   at Newtonsoft.Json.Utilities.CollectionUtils.IsDictionaryType(Type type)
   at Newtonsoft.Json.Serialization.DefaultContractResolver.CreateContract(Type objectType)
   at Newtonsoft.Json.Serialization.DefaultContractResolver.ResolveContract(Type type)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at TShockAPI.ConfigFile.Read(Stream stream)
   at TShockAPI.ConfigFile.Read(String path)
   at TShockAPI.FileTools.SetupConfig()
   at TShockAPI.TShock.Initialize()
   --- End of inner exception stack trace ---
   at TShockAPI.TShock.Initialize()
   at TerrariaApi.Server.ServerApi.LoadPlugins()
   --- End of inner exception stack trace ---
   at TerrariaApi.Server.ServerApi.LoadPlugins()
   at TerrariaApi.Server.ServerApi.Initialize(String[] commandLineArgs, Main game)
   at Terraria.ProgramServer.InnerStart(String[] args)
[07/06/15 16:06:58] [Server API] Verbose: TerrariaApi - Server v1.18.0.0 started.
[07/06/15 16:06:58] [Server API] Verbose: 	Command line: "C:\Users\Server\Desktop\Tshock Terraria Server\TerrariaServer.exe" 
[07/06/15 16:06:58] [Server API] Verbose: 	OS: Microsoft Windows NT 6.1.7601 Service Pack 1 (64bit: True)
[07/06/15 16:06:58] [Server API] Verbose: 	Mono: False
[07/06/15 16:06:58] [Server API] Error: Startup aborted due to an exception in the Server API initialization:
System.InvalidOperationException: Plugin "TShock" has thrown an exception during initialization. ---> System.Exception: Fatal TShock initialization exception. See inner exception for details. ---> System.TypeLoadException: Could not load type 'System.Collections.Generic.IReadOnlyDictionary`2' from assembly 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'.
   at Newtonsoft.Json.Utilities.CollectionUtils.IsDictionaryType(Type type)
   at Newtonsoft.Json.Serialization.DefaultContractResolver.CreateContract(Type objectType)
   at Newtonsoft.Json.Serialization.DefaultContractResolver.ResolveContract(Type type)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at TShockAPI.ConfigFile.Read(Stream stream)
   at TShockAPI.ConfigFile.Read(String path)
   at TShockAPI.FileTools.SetupConfig()
   at TShockAPI.TShock.Initialize()
   --- End of inner exception stack trace ---
   at TShockAPI.TShock.Initialize()
   at TerrariaApi.Server.ServerApi.LoadPlugins()
   --- End of inner exception stack trace ---
   at TerrariaApi.Server.ServerApi.LoadPlugins()
   at TerrariaApi.Server.ServerApi.Initialize(String[] commandLineArgs, Main game)
   at Terraria.ProgramServer.InnerStart(String[] args)
[07/06/15 16:07:08] [Server API] Verbose: TerrariaApi - Server v1.18.0.0 started.
[07/06/15 16:07:08] [Server API] Verbose: 	Command line: "C:\Users\Server\Desktop\Tshock Terraria Server\TerrariaServer.exe" 
[07/06/15 16:07:08] [Server API] Verbose: 	OS: Microsoft Windows NT 6.1.7601 Service Pack 1 (64bit: True)
[07/06/15 16:07:08] [Server API] Verbose: 	Mono: False
[07/06/15 16:07:08] [Server API] Error: Startup aborted due to an exception in the Server API initialization:
System.InvalidOperationException: Plugin "TShock" has thrown an exception during initialization. ---> System.Exception: Fatal TShock initialization exception. See inner exception for details. ---> System.TypeLoadException: Could not load type 'System.Collections.Generic.IReadOnlyDictionary`2' from assembly 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'.
   at Newtonsoft.Json.Utilities.CollectionUtils.IsDictionaryType(Type type)
   at Newtonsoft.Json.Serialization.DefaultContractResolver.CreateContract(Type objectType)
   at Newtonsoft.Json.Serialization.DefaultContractResolver.ResolveContract(Type type)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at TShockAPI.ConfigFile.Read(Stream stream)
   at TShockAPI.ConfigFile.Read(String path)
   at TShockAPI.FileTools.SetupConfig()
   at TShockAPI.TShock.Initialize()
   --- End of inner exception stack trace ---
   at TShockAPI.TShock.Initialize()
   at TerrariaApi.Server.ServerApi.LoadPlugins()
   --- End of inner exception stack trace ---
   at TerrariaApi.Server.ServerApi.LoadPlugins()
   at TerrariaApi.Server.ServerApi.Initialize(String[] commandLineArgs, Main game)
   at Terraria.ProgramServer.InnerStart(String[] args)
[07/06/15 16:07:23] [Server API] Verbose: TerrariaApi - Server v1.18.0.0 started.
[07/06/15 16:07:23] [Server API] Verbose: 	Command line: "C:\Users\Server\Desktop\Tshock Terraria Server\TerrariaServer.exe" 
[07/06/15 16:07:23] [Server API] Verbose: 	OS: Microsoft Windows NT 6.1.7601 Service Pack 1 (64bit: True)
[07/06/15 16:07:23] [Server API] Verbose: 	Mono: False
[07/06/15 16:07:24] [Server API] Error: Startup aborted due to an exception in the Server API initialization:
System.InvalidOperationException: Plugin "TShock" has thrown an exception during initialization. ---> System.Exception: Fatal TShock initialization exception. See inner exception for details. ---> System.TypeLoadException: Could not load type 'System.Collections.Generic.IReadOnlyDictionary`2' from assembly 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'.
   at Newtonsoft.Json.Utilities.CollectionUtils.IsDictionaryType(Type type)
   at Newtonsoft.Json.Serialization.DefaultContractResolver.CreateContract(Type objectType)
   at Newtonsoft.Json.Serialization.DefaultContractResolver.ResolveContract(Type type)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at TShockAPI.ConfigFile.Read(Stream stream)
   at TShockAPI.ConfigFile.Read(String path)
   at TShockAPI.FileTools.SetupConfig()
   at TShockAPI.TShock.Initialize()
   --- End of inner exception stack trace ---
   at TShockAPI.TShock.Initialize()
   at TerrariaApi.Server.ServerApi.LoadPlugins()
   --- End of inner exception stack trace ---
   at TerrariaApi.Server.ServerApi.LoadPlugins()
   at TerrariaApi.Server.ServerApi.Initialize(String[] commandLineArgs, Main game)
   at Terraria.ProgramServer.InnerStart(String[] args)
[07/06/15 16:07:35] [Server API] Verbose: TerrariaApi - Server v1.18.0.0 started.
[07/06/15 16:07:35] [Server API] Verbose: 	Command line: "C:\Users\Server\Desktop\Tshock Terraria Server\TerrariaServer.exe" 
[07/06/15 16:07:35] [Server API] Verbose: 	OS: Microsoft Windows NT 6.1.7601 Service Pack 1 (64bit: True)
[07/06/15 16:07:35] [Server API] Verbose: 	Mono: False
[07/06/15 16:07:35] [Server API] Error: Startup aborted due to an exception in the Server API initialization:
System.InvalidOperationException: Plugin "TShock" has thrown an exception during initialization. ---> System.Exception: Fatal TShock initialization exception. See inner exception for details. ---> System.TypeLoadException: Could not load type 'System.Collections.Generic.IReadOnlyDictionary`2' from assembly 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'.
   at Newtonsoft.Json.Utilities.CollectionUtils.IsDictionaryType(Type type)
   at Newtonsoft.Json.Serialization.DefaultContractResolver.CreateContract(Type objectType)
   at Newtonsoft.Json.Serialization.DefaultContractResolver.ResolveContract(Type type)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at TShockAPI.ConfigFile.Read(Stream stream)
   at TShockAPI.ConfigFile.Read(String path)
   at TShockAPI.FileTools.SetupConfig()
   at TShockAPI.TShock.Initialize()
   --- End of inner exception stack trace ---
   at TShockAPI.TShock.Initialize()
   at TerrariaApi.Server.ServerApi.LoadPlugins()
   --- End of inner exception stack trace ---
   at TerrariaApi.Server.ServerApi.LoadPlugins()
   at TerrariaApi.Server.ServerApi.Initialize(String[] commandLineArgs, Main game)
   at Terraria.ProgramServer.InnerStart(String[] args)
[07/06/15 16:07:44] [Server API] Verbose: TerrariaApi - Server v1.18.0.0 started.
[07/06/15 16:07:44] [Server API] Verbose: 	Command line: "C:\Users\Server\Desktop\Tshock Terraria Server\TerrariaServer.exe" 
[07/06/15 16:07:44] [Server API] Verbose: 	OS: Microsoft Windows NT 6.1.7601 Service Pack 1 (64bit: True)
[07/06/15 16:07:44] [Server API] Verbose: 	Mono: False
[07/06/15 16:07:44] [Server API] Error: Startup aborted due to an exception in the Server API initialization:
System.InvalidOperationException: Plugin "TShock" has thrown an exception during initialization. ---> System.Exception: Fatal TShock initialization exception. See inner exception for details. ---> System.TypeLoadException: Could not load type 'System.Collections.Generic.IReadOnlyDictionary`2' from assembly 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'.
   at Newtonsoft.Json.Utilities.CollectionUtils.IsDictionaryType(Type type)
   at Newtonsoft.Json.Serialization.DefaultContractResolver.CreateContract(Type objectType)
   at Newtonsoft.Json.Serialization.DefaultContractResolver.ResolveContract(Type type)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at TShockAPI.ConfigFile.Read(Stream stream)
   at TShockAPI.ConfigFile.Read(String path)
   at TShockAPI.FileTools.SetupConfig()
   at TShockAPI.TShock.Initialize()
   --- End of inner exception stack trace ---
   at TShockAPI.TShock.Initialize()
   at TerrariaApi.Server.ServerApi.LoadPlugins()
   --- End of inner exception stack trace ---
   at TerrariaApi.Server.ServerApi.LoadPlugins()
   at TerrariaApi.Server.ServerApi.Initialize(String[] commandLineArgs, Main game)
   at Terraria.ProgramServer.InnerStart(String[] args)
[07/06/15 16:09:59] [Server API] Verbose: TerrariaApi - Server v1.18.0.0 started.
[07/06/15 16:09:59] [Server API] Verbose: 	Command line: "C:\Users\Server\Desktop\Tshock Terraria Server\TerrariaServer.exe" 
[07/06/15 16:09:59] [Server API] Verbose: 	OS: Microsoft Windows NT 6.1.7601 Service Pack 1 (64bit: True)
[07/06/15 16:09:59] [Server API] Verbose: 	Mono: False
[07/06/15 16:09:59] [Server API] Error: Startup aborted due to an exception in the Server API initialization:
System.InvalidOperationException: Plugin "TShock" has thrown an exception during initialization. ---> System.Exception: Fatal TShock initialization exception. See inner exception for details. ---> System.TypeLoadException: Could not load type 'System.Collections.Generic.IReadOnlyDictionary`2' from assembly 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'.
   at Newtonsoft.Json.Utilities.CollectionUtils.IsDictionaryType(Type type)
   at Newtonsoft.Json.Serialization.DefaultContractResolver.CreateContract(Type objectType)
   at Newtonsoft.Json.Serialization.DefaultContractResolver.ResolveContract(Type type)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at TShockAPI.ConfigFile.Read(Stream stream)
   at TShockAPI.ConfigFile.Read(String path)
   at TShockAPI.FileTools.SetupConfig()
   at TShockAPI.TShock.Initialize()
   --- End of inner exception stack trace ---
   at TShockAPI.TShock.Initialize()
   at TerrariaApi.Server.ServerApi.LoadPlugins()
   --- End of inner exception stack trace ---
   at TerrariaApi.Server.ServerApi.LoadPlugins()
   at TerrariaApi.Server.ServerApi.Initialize(String[] commandLineArgs, Main game)
   at Terraria.ProgramServer.InnerStart(String[] args)
[07/06/15 16:10:34] [Server API] Verbose: TerrariaApi - Server v1.18.0.0 started.
[07/06/15 16:10:34] [Server API] Verbose: 	Command line: "C:\Users\Server\Desktop\Tshock Terraria Server\TerrariaServer.exe" 
[07/06/15 16:10:34] [Server API] Verbose: 	OS: Microsoft Windows NT 6.1.7601 Service Pack 1 (64bit: True)
[07/06/15 16:10:34] [Server API] Verbose: 	Mono: False
[07/06/15 16:10:34] [Server API] Error: Startup aborted due to an exception in the Server API initialization:
System.InvalidOperationException: Plugin "TShock" has thrown an exception during initialization. ---> System.Exception: Fatal TShock initialization exception. See inner exception for details. ---> System.TypeLoadException: Could not load type 'System.Collections.Generic.IReadOnlyDictionary`2' from assembly 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'.
   at Newtonsoft.Json.Utilities.CollectionUtils.IsDictionaryType(Type type)
   at Newtonsoft.Json.Serialization.DefaultContractResolver.CreateContract(Type objectType)
   at Newtonsoft.Json.Serialization.DefaultContractResolver.ResolveContract(Type type)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at TShockAPI.ConfigFile.Read(Stream stream)
   at TShockAPI.ConfigFile.Read(String path)
   at TShockAPI.FileTools.SetupConfig()
   at TShockAPI.TShock.Initialize()
   --- End of inner exception stack trace ---
   at TShockAPI.TShock.Initialize()
   at TerrariaApi.Server.ServerApi.LoadPlugins()
   --- End of inner exception stack trace ---
   at TerrariaApi.Server.ServerApi.LoadPlugins()
   at TerrariaApi.Server.ServerApi.Initialize(String[] commandLineArgs, Main game)
   at Terraria.ProgramServer.InnerStart(String[] args)

**Comment by WhiteXZ** [comment]
Do you have .NET 4.5 installed?

**Comment by wrentrillogy** [comment]
Thanks I just installed I had 4.0 but still same error maybe I need to restart my server pc?

**Comment by wrentrillogy** [comment]
Yea I installed 4.5.2 and still wont run

**Comment by wrentrillogy** [comment]
Ok fresh install of tshock after the update and restart I'm good now thanks very much :)

**Comment by WhiteXZ** [comment]
Good stuff
