### ISSUE TITLE
Server crashes Windows

### ISSUE THREAD

**Issue by cokll** [NyxStudios/TShock#971]
[07/08/15 19:26:30] [Server API] Verbose: TerrariaApi - Server v1.18.0.0 started.
[07/08/15 19:26:31] [Server API] Verbose: 	Command line: D:\TerrariaServer\TerrariaServer.exe -port 25570 -players 8 -world test -autocreate 3 -secure
[07/08/15 19:26:31] [Server API] Verbose: 	OS: Microsoft Windows NT 6.1.7601 Service Pack 1 (64bit: True)
[07/08/15 19:26:31] [Server API] Verbose: 	Mono: False
[07/08/15 19:26:31] [Server API] Verbose: Listening on port 25570.
[07/08/15 19:26:31] [Server API] Verbose: World set for auto loading: testgmod
[07/08/15 19:26:31] [Server API] Info: Plugin TShock v4.3.1.0 (by The TShock Team) initiated.
[07/08/15 19:26:33] [Server API] Error: Server crashed due to an unhandled exception:
System.NullReferenceException: Object reference not set to an instance of an object.
   at Terraria.Main.get_expertMode()
   at Terraria.NPC.SetDefaults(Int32 Type, Single scaleOverride)
   at Terraria.NPC.SetDefaults(String Name)
   at Terraria.NPC.netDefaults(Int32 type)
   at Terraria.Main.InitLifeBytes()
   at Terraria.Main.Initialize()
   at Terraria.Main.DedServ()
   at Terraria.ProgramServer.InnerStart(String[] args)

**Comment by sotn0r** [comment]
Happens when the world file specified in the -world parameter doesnt exist.

**Comment by Ijwu** [comment]
Attempt to use `-autocreate` but note that it may be broken as noted in #965
