### ISSUE TITLE
Version 4.3.2 error

### ISSUE THREAD

**Issue by Bud1980** [NyxStudios/TShock#986]
[07/10/15 11:10:30] [Server API] Error: Server crashed due to an unhandled exception:
System.InvalidOperationException: Failed to compare two elements in the array. ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at Terraria.Main.WorldListSortMethod(WorldFileData data1, WorldFileData data2)
   at System.Array.FunctorComparer`1.Compare(T x, T y)
   at System.Collections.Generic.ArraySortHelper`1.SwapIfGreater(T[] keys, IComparer`1 comparer, Int32 a, Int32 b)
   at System.Collections.Generic.ArraySortHelper`1.DepthLimitedQuickSort(T[] keys, Int32 left, Int32 right, IComparer`1 comparer, Int32 depthLimit)
   at System.Collections.Generic.ArraySortHelper`1.Sort(T[] keys, Int32 index, Int32 length, IComparer`1 comparer)
   --- End of inner exception stack trace ---
   at System.Collections.Generic.ArraySortHelper`1.Sort(T[] keys, Int32 index, Int32 length, IComparer`1 comparer)
   at System.Array.Sort[T](T[] array, Int32 index, Int32 length, IComparer`1 comparer)
   at System.Collections.Generic.List`1.Sort(Comparison`1 comparison)
   at Terraria.Main.LoadWorlds()
   at Terraria.Main.DedServ()
   at Terraria.ProgramServer.InnerStart(String[] args)

**Comment by nicatronTg** [comment]
See [here](https://tshock.co/xf/index.php?threads/tshock-4-3-2-api-v1-19-prerelease-for-terraria-1-3-0-4.3839/#post-40851).
