### ISSUE TITLE
Server crashes upon starting with latest release

### ISSUE THREAD

**Issue by imasonaz** [NyxStudios/TShock#996]
I had migrated to the first "release" for 1.3 (not beta), after migrating, I then updated to the latest version today to hopefully fix some issues with NPCs, quests, etc. Upon startup, I get the following:
```
[07/11/15 23:19:57] [Server API] Verbose: TerrariaApi - Server v1.19.0.0 started.
[07/11/15 23:19:57] [Server API] Verbose: 	Command line: "C:\Users\Administrator\Desktop\Terraria 1.3\TerrariaServer.exe" 
[07/11/15 23:19:57] [Server API] Verbose: 	OS: Microsoft Windows NT 6.2.9200.0 (64bit: True)
[07/11/15 23:19:57] [Server API] Verbose: 	Mono: False
[07/11/15 23:19:59] [Server API] Info: Plugin TShock v4.3.4.0 (by The TShock Team) initiated.
[07/11/15 23:20:07] [Server API] Error: Server crashed due to an unhandled exception:
System.InvalidOperationException: Failed to compare two elements in the array. ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at Terraria.Main.WorldListSortMethod(WorldFileData data1, WorldFileData data2)
   at System.Array.FunctorComparer`1.Compare(T x, T y)
   at System.Collections.Generic.ArraySortHelper`1.DepthLimitedQuickSort(T[] keys, Int32 left, Int32 right, IComparer`1 comparer, Int32 depthLimit)
   at System.Collections.Generic.ArraySortHelper`1.Sort(T[] keys, Int32 index, Int32 length, IComparer`1 comparer)
   --- End of inner exception stack trace ---
   at System.Collections.Generic.ArraySortHelper`1.Sort(T[] keys, Int32 index, Int32 length, IComparer`1 comparer)
   at System.Array.Sort[T](T[] array, Int32 index, Int32 length, IComparer`1 comparer)
   at System.Collections.Generic.List`1.Sort(Comparison`1 comparison)
   at Terraria.Main.LoadWorlds()
   at Terraria.Main.DedServ()
   at Terraria.ProgramServer.InnerStart(String[] args)
```

**Comment by nicatronTg** [comment]
Please post on the forums and read the ultimate help guide. We already have addressed this several times, and make it clear that Github issues is not the place for support.
